trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo 'FROM alpine:latest' >> Dockerfile
    echo 'RUN apk --update add python3' >> Dockerfile
    echo 'COPY . /usr/src/app' >> Dockerfile
    echo 'CMD ["python3", "/usr/src/app/main.py"]' >> Dockerfile
  displayName: 'Create Docker File'

- script: docker build -t multitabledary .
  displayName: 'Build Docker Image'

- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: 'login'
    containerRegistry: 'docker-registry'
    username: '$(dockerhub_username)'
    password: '$(dockerhub_password)'

- script: docker tag multitabledary winterzone2/multiplicationtable:v2
  displayName: 'Tag Docker Image'

- script: docker push winterzone2/multiplicationtable:v2
  displayName: 'Push Docker Image'